language: ruby
services:
  - docker
rvm:
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
  - docker-compose build
script:
  - bundle exec rake
  - docker-compose run ruby_server bundle exec rake
  - bundle exec rubocop
notifications:
  email:
    recipients:
      - inferno@groups.mitre.org
    on_failure: change
