version: '3'
services:
  # the main ruby server
  ruby_server:
    # build the image from ./Dockerfile (this installs the dependencies into the image)
    build:
      context: ./
    # map the project directory into the running container
    volumes:
      - .:/var/www/inferno
    # expose the internal application to direct HTTP requests
    #ports:
    #  - "4567:8080"
    # run the application
    working_dir: /var/www/inferno
    command: rackup -o 0.0.0.0
  nginx_server:
    image: nginx
    volumes:
      - ./deployment-files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    command: [nginx, '-g', 'daemon off;']
    links:
      - ruby_server:ruby_server
    depends_on:
      - ruby_server